name: Selenium Tests - SUT saucedemo
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install Google Chrome
        run: |
          
          chmod +x ./scripts/InstallChrome.sh
          
                      ./scripts/InstallChrome.sh
      - name: Build with Maven
        run: mvn clean verify