name: Selenium Tests - SUT saucedemo

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          sudo apt-get install -y chromium-browser

          # Install Microsoft Edge from the Microsoft repository
          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge-dev.list
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-dev

      - name: Check Chrome version
        run: chromium-browser --version

      - name: Check Firefox version
        run: firefox --version

      - name: Check Microsoft Edge version
        run: microsoft-edge-dev --version

      - name: Build with Maven
        run: mvn clean verify