name: Selenium_Tests_SUT_saucedemo

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Allure
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.zip
          unzip allure-commandline-2.24.0.zip -d /opt/

      - name: Set up Microsoft Edge
        uses: browser-actions/setup-edge@v1

      - name: Print Edge version
        run: |
          echo "Microsoft Edge Version:"
          msedge --version

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Print Firefox version
        run: firefox --version

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Print Chrome version
        run: google-chrome --version

      - name: Build with Maven
        run: mvn clean verify

      - name: Generate Allure Report
        if: always()
        run: |
          export PATH=$PATH:/opt/allure-2.24.0/bin
          source ~/.bashrc
          allure generate target/allure-results --clean

      - name: 'Upload Artifact Allure Report'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 14

      - name: 'Upload Artifact Log'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Framework Log
          path: target/logger.log
          retention-days: 14

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            TEST-*.xml